#!/bin/bash
#PBS -l nodes=1:ppn=8:dc2,walltime=2:00:00
#PBS -N LBmatlab
#PBS -V

if [ $ENV == "IUHPC" ]; then
    module load matlab
fi

matlab -nodisplay -nosplash -r main

if [ -s spectrum.json ] && [ -s eigenvectors.h5 ]
then
	echo 0 > finished
else
	echo "files missing"
	echo 1 > finished
	exit 1
fi
